package com.mycompany.myapp;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Button;
import com.codename1.ui.Component;
import com.codename1.ui.Graphics;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BorderLayout;



/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Main {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/Theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        View();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

    private void View()
    {
        Form form = new Form("MoodMovie");
//        form.add(BorderLayout.CENTER,new Component(){
//            @Override
//            public void paint(Graphics g) {
//                g.setColor(0x000000);
//                g.fillRect(getX(), getY(), getWidth(), getHeight());
//            }
//        });
        form.addComponent(new Label("Bienvenue sur MoodMovie !"));
        
        Button begin = new Button("Commencer");
        form.add(begin);
        String title = "Bienvenue dans l'application";
        begin.addActionListener((e)->Dialog.show(title, "hi","ok",null));
        
        form.show();
    }
}
